# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 01:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20170222_1749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='description',
            old_name='course_id',
            new_name='course',
        ),
    ]
